{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "feast-operator.fullname" . }}-controller-manager-metrics-monitor
  namespace: {{ include "feast-operator.namespace" . }}
  labels:
    {{- include "feast-operator.labels" . | nindent 4 }}
    {{- with .Values.prometheus.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (include "feast-operator.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.prometheus.serviceMonitor.timeout }}
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      {{- include "feast-operator.selectorLabels" . | nindent 6 }}
{{- end }}